### ISSUE TITLE
Powershell core on linux

### ISSUE THREAD

**Issue by dinodipardo** [microsoft/PowerShellForGitHub#423] opened 2023-11-19 15:10 UTC
#### Issue Details
Get-GitHubRepository (and other commands) fail (Powershell 7/debian)
Exception calling "Serialize" with "2" argument(s): "BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information."

#### Steps to reproduce the issue
```Install debian (virtual/WSL)
   install powershell
   install PowerShellForGitHub
   execute Get-GitHubRepository -OrganizationName Microsoft
   # Include your repro steps here
```

#### Verbose logs showing the problem

Exception calling "Serialize" with "2" argument(s): "BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information."

#### Operating System
Name                           Value
----                           -----
OSVersion                      Unix 5.15.133.1
Is 64-bit                      True
Current culture                en-US
Current UI culture             en-US

#### PowerShell Version
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Debian GNU/Linux 11 (bullseye)
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

#### Module Version
Running: 0.16.1
Installed: 0.16.1

**Comment by HowardWolosky** [comment] 2023-11-20 22:53
Dupe of #413

**Closed by HowardWolosky** 2023-11-20 22:53 UTC
Labels: duplicate

**Comment by HowardWolosky** [comment] 2023-11-21 19:27
If you update to 0.17.0 your problem should be fixed: https://www.powershellgallery.com/packages/PowerShellForGitHub/0.17.0
