### ISSUE TITLE
Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by Hern-Tyler** [microsoft/PowerShellForGitHub#147] opened 2020-02-27 20:32 UTC
I was trying to create a small gui script to create a repo with a few default settings. 
1. Steps to reproduce: Get-GitHubRepository
2. Expected to see a list of repositories
3. What I saw instead:
Get-GitHubRepository : The term 'Write-InvocationLog' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was 
included, verify that the path is correct and try again.
At line:1 char:1
+ Get-GitHubRepository
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Write-InvocationLog:String) [Get-GitHubRepository], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Get-GitHubRepository

**Comment by HowardWolosky** [comment] 2020-02-27 20:40
Hi @Hern-Tyler,

I can't reproduce your problem.  `Write-InvocationLog` is a part of the module, a non-exported function [located in the Helpers.ps1 file](https://github.com/microsoft/PowerShellForGitHub/blob/master/Helpers.ps1#L403-L476).  As long as the command is being run out of the module, it should be able to find it just fine.

* What version of PowerShellForGitHub are you using?
* How did you install it?
* What version of PowerShell are you running?

**Comment by Hern-Tyler** [comment] 2020-02-27 20:46
PowerShellForGitHub Version: 0.9.2
Installed with Install-Module -Name PowerShellForGitHub
Powershell Version: 1.0

**Comment by HowardWolosky** [comment] 2020-02-27 20:47
> Powershell Version: 1.0

That doesn't sound quite right.  Can you provide the output of `$PSVersionTable`?

**Comment by Hern-Tyler** [comment] 2020-02-27 20:52
My apologies, it's 5.1.18362.628

**Comment by HowardWolosky** [comment] 2020-02-27 21:11
Ok, we're working off of the same PS version.  Do any other commands work?  That `Write-InvocationLog` function is writing an entry into your log file, which defaults to your Documents directory (`Get-GitHubConfiguration -Name LogPath`).  Do you have a `PowerShellForGitHub.log` file there?  If so, does it have any entries like this:

```
2020-02-27 12:37:55 : howard : VERBOSE : [0.9.2] Executing: Get-GitHubRepository -OwnerName "microsoft" -RepositoryName "PowerShelLForGitHub"
```

In theory, you could temporarily disable logging to see if that gets you past the problem, but it shouldn't be necessary (and I'd like to better understand why you're hitting this issue):

`Set-GitHubConfiguration -DisableLogging`

**Comment by Hern-Tyler** [comment] 2020-02-27 21:18
Yes, mine has the following:
`2020-02-27 11:16:23 : thern : VERBOSE : [0.9.2] Executing: Set-GitHubAuthentication `
and
`2020-02-27 11:16:23 : thern : INFORMATIONAL : Please provide your GitHub API Token in the Password field.  You can enter anything in the username field (it will be ignored).  ***The token is being cached across PowerShell sessions.  To clear caching, call Clear-GitHubAuthentication.***`

**Comment by HowardWolosky** [comment] 2020-02-27 21:35
Hmmm....`Set-GitHubAuthentication` is calling `Write-InvocationLog` as well as the very first thing, clearly without issue.

Are we removing your script from the debugging equation here?  If you directly call

```Get-GitHubRepository -OwnerName "microsoft" -RepositoryName "PowerShelLForGitHub"```

from the command-line, is it returning that same error?

**Comment by Hern-Tyler** [comment] 2020-02-27 21:40
I included everything for clarity, but there is a unique error at the end.

From the command-line, `Get-GitHubRepository -OwnerName "microsoft" -RepositoryName "PowerShelLForGitHub"` is returning the following:
`DONE (FAILED) - Operation took 1 second(s) [Getting repo PowerShelLForGitHub]
Telemetry is currently enabled.  It can be disabled by calling "Set-GitHubConfiguration -DisableTelemetry". Refer to USAGE.md#telemetry for more information. Stop seeing this message in the future by calling "Set-GitHubConfiguration -SuppressTelemetryReminder".
DONE - Operation took 5 second(s) [Retrieving nuget package: Microsoft.Bcl.Async]
To avoid this download delay in the future, copy the following file:
  [C:\Users\thern\AppData\Local\Temp\65e875e9-f0ad-4475-a8ec-bee408b664ab\Microsoft.Bcl.Async.1.0.168\lib\net40\Microsoft.Threading.Tasks.dll]
either to:
  [C:\Program Files\WindowsPowerShell\Modules\PowerShellForGitHub\0.9.2]
or to:
  a directory of your choosing, and store that directory as 'AssemblyPath' with 'Set-GitHubConfiguration'
DONE - Operation took 3 second(s) [Retrieving nuget package: Microsoft.Diagnostics.Tracing.EventSource.Redist]
To avoid this download delay in the future, copy the following file:
  [C:\Users\thern\AppData\Local\Temp\65e875e9-f0ad-4475-a8ec-bee408b664ab\Microsoft.Diagnostics.Tracing.EventSource.Redist.1.1.24\lib\net35\Microsoft.Diagnostics.Tracing.EventSource.dll]
either to:
  [C:\Program Files\WindowsPowerShell\Modules\PowerShellForGitHub\0.9.2]
or to:
  a directory of your choosing, and store that directory as 'AssemblyPath' with 'Set-GitHubConfiguration'
DONE - Operation took 2 second(s) [Retrieving nuget package: Microsoft.ApplicationInsights]
To avoid this download delay in the future, copy the following file:
  [C:\Users\thern\AppData\Local\Temp\65e875e9-f0ad-4475-a8ec-bee408b664ab\Microsoft.ApplicationInsights.2.0.1\lib\net45\Microsoft.ApplicationInsights.dll]
either to:
  [C:\Program Files\WindowsPowerShell\Modules\PowerShellForGitHub\0.9.2]
or to:
  a directory of your choosing, and store that directory as 'AssemblyPath' with 'Set-GitHubConfiguration'
The request was aborted: Could not create SSL/TLS secure channel.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellForGitHub\0.9.2\GitHubCore.ps1:527 char:9
+         throw $newLineOutput
+         ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (The request was...secure channel.:String) [], RuntimeException
    + FullyQualifiedErrorId : The request was aborted: Could not create SSL/TLS secure channel.`

I included everything for clarity, but there is a unique error at the end.

**Comment by HowardWolosky** [comment] 2020-02-27 21:45
Ok...so the issue has nothing to do with `Write-InvocationLog`.  I'm not sure why you're seeing that error about "Could not create SSL/TLS secure channel." We [specifically request](https://github.com/microsoft/PowerShellForGitHub/blob/master/GitHubCore.ps1#L262) TLS 1.2 in order to meet the security requirements.

Is there any chance you have a proxy running on your box, or Fiddler, or anything else that might be messing with your network connection?

**Comment by HowardWolosky** [comment] 2020-02-27 21:47
Also, did you alter the value for `ApiHostName` (via Set-GitHubConfiguration`?  Any chance you're not accessing GitHub.com, but rather an offsite enterprise installation of GitHub?

**Comment by Hern-Tyler** [comment] 2020-02-27 21:52
I am unaware of anything that might be causing network issues. I appreciate your patience with me, I'm still fairly new with powershell in general.

How can I check to see if I've changed the `ApiHostName`?

**Comment by HowardWolosky** [comment] 2020-02-27 21:56
What does ```Get-GitHubConfiguration -Name ApiHostName``` return?

**Comment by Hern-Tyler** [comment] 2020-02-27 22:01
it just returns `Inc`

**Comment by HowardWolosky** [comment] 2020-02-27 22:37
That appears to be your problem.  You have an invalid `ApiHost`.  That would have had to be something that you did manually, as the default value should be `github.com`.

Here's what I suggest...  Run ```Reset-GitHubConfiguration```.

That will fix up your ApiHost as well as any other incorrect configuration changes you may have inadvertently made.  After you do that, running `Get-GitHubConfiguration -Name ApiHost` should return `github.com`, and running ```Get-GitHubRepository -OwnerName "microsoft" -RepositoryName "PowerShelLForGitHub"``` should work just fine as well.

**Comment by Hern-Tyler** [comment] 2020-02-28 14:10
I ran `Reset-GithubConfiguration` and that seemed to clear things up a bit. Then, I ran `Get-GithubConfiguration -Name ApiHostName` and that did return `github.com`, however; running `Get-GitHubRepository -OwnerName "microsoft" -RepositoryName "PowerShelLForGitHub"` returns `A parameter cannot be found that matches parameter name 'OwnerName'.`

**Comment by HowardWolosky** [comment] 2020-02-28 15:33
Is there any additional error information in your log file?  Again, this is quite odd and is pointing to something weird with your installation.

If you type `Get-GitHubRepository<space>-<tab>`, does it auto-complete `-OwnerName` as the first parameter option? (that's a space, then the dash (`-`) then a `<tab>`)

**Comment by Hern-Tyler** [comment] 2020-02-28 15:59
I tried this again and it actually began to run, although it resulted in the following error this time:

> The remote server returned an error: (401) Unauthorized.
>401 | Unauthorized
>Bad credentials | https://developer.github.com/v3
>At C:\Program Files\WindowsPowerShell\Modules\PowerShellForGitHub\0.9.2\GitHubCore.ps1:527 char:9
>+         throw $newLineOutput
>+         ~~~~~~~~~~~~~~~~~~~~
>    + CategoryInfo          : OperationStopped: (The remote serv...r.github.com/v3:String) [], RuntimeException
    + FullyQualifiedErrorId : The remote server returned an error: (401) Unauthorized.
401 | Unauthorized
Bad credentials | https://developer.github.com/v3

Also, my log seems to have a lot more information in it this time. Is there a certain piece of information that would be useful to you?

**Comment by HowardWolosky** [comment] 2020-02-28 16:12
Now you're just having Auth issues. Follow the [configuration steps](https://github.com/microsoft/PowerShellForGitHub/blob/master/README.md#configuration) to set up a valid Auth token.

**Comment by HowardWolosky** [comment] 2020-05-12 18:22
@Hern-Tyler - I'm closing this issue now as it seems that your problems have been resolved.  Please let us know if you're still having trouble.

**Closed by HowardWolosky** 2020-05-12 18:22 UTC
Labels: support
